const CONTRACT_PERWALLET_MAX_MINT_AMOUNT = 12;
const CONTRACT_NFT_TOTAL_AMOUNT = 5000;
const CONTRACT_NFT_PER_PRICE = 0.002;
const FREE_MINT_AMOUNT = 2000;
const MAX_FREE_MINT_PER_ADDR = 2;
const CONTRACT_NFT_OFFICIAL_NAME = "web3-general-web";
const CONTRACT_NFT_SAMBLE_NAME = "web3-general-web";
const CONTRACT_STATUS = {
  'OFF': '0',
  'ON': '1',
  'SOLD_OUT': '2',
}
const SOCIAL_MEDIA_URL = {
  'OPENSEA': 'https://opensea.io/collection/',
  'ETHERSCAN': 'https://etherscan.io/address/',
  'TWITTER': 'https://twitter.com/',
}

const THEME_MODE = {
  'LIGHT': 'light',
  'DARK': 'dark'
}

export {
  CONTRACT_PERWALLET_MAX_MINT_AMOUNT,
  CONTRACT_NFT_TOTAL_AMOUNT,
  CONTRACT_NFT_PER_PRICE,
  CONTRACT_STATUS,
  SOCIAL_MEDIA_URL,
  CONTRACT_NFT_OFFICIAL_NAME,
  CONTRACT_NFT_SAMBLE_NAME,
  FREE_MINT_AMOUNT,
  MAX_FREE_MINT_PER_ADDR,
  THEME_MODE
}